Re-throw errors from octokit
Fixes this error for 4xx responses:

    TypeError: Cannot read property 'meta' of undefined
        42 |   octokit.hook.after('request', (result, options) => {
        43 |     const {method, url, headers, ...params} = options
      > 44 |     const msg = `GitHub request: ${method} ${url} -
${result.meta.status}`
        45 |     logger.debug({params}, msg)
        46 |   })
        47 |   octokit.paginate = paginate.bind(null, octokit)

        at EnhancedGitHubClient.octokit.hook.after (lib/github.js:44:62)
        at invokeAfterHook
(node_modules/before-after-hook/lib/register.js:96:12)
            at Array.map (<anonymous>)
        at node_modules/before-after-hook/lib/register.js:60:35

    at Object.<anonymous> (node_modules/expect/build/index.js:179:51)
        at Generator.throw (<anonymous>)
    at step (node_modules/expect/build/index.js:43:727)
    at node_modules/expect/build/index.js:43:926